import type { GetServerSidePropsContext, NextPage } from 'next';
import Head from 'next/head';
import BaseButton from '../components/buttons/baseButton';
import HistoryCard from '../components/cards/history';
import MatchCard from '../components/cards/match';
import Tabs from '../components/tabs';
import styles from './styles.module.css';
import UserSticker from '../components/userSticker';
import { useAuth } from 'src/hooks/useAuth';
import { Goal, Match, User } from 'src/types';
import { withAuth } from 'src/middleware/withAuth';
import { getGoalsFromUser, getHistoryMatchesByuser, getMatchesByUser } from 'src/services/matchService';
import { useEffect, useState } from 'react';

export const getServerSideProps = withAuth();

const Home: NextPage = () => {
  const { user } = useAuth();

  const [matches, setMatches] = useState<Array<Match>>([]);
  const [historyMatches, setHistoryMatches] = useState<Array<Match>>([]);
  const [userGoals, setUserGoals] = useState<Array<Goal>>([]);

  const getMatches = async () => {
    const m = await getMatchesByUser(user as User);

    setMatches(m);
  }

  const getHistoryMatches = async () => {
    const _matches = await getHistoryMatchesByuser(user as User);

    setHistoryMatches(_matches);
  }

  const getUserGoals = async () => {
    const _goals = await getGoalsFromUser(user as User);

    setUserGoals(_goals);
  }

  useEffect(() => {

    if (user) {
      if (matches.length == 0) {
        getMatches();
      }

      if (historyMatches.length == 0) {
        getHistoryMatches();
      }

      if (userGoals.length == 0) {
        getUserGoals();
      }
    }
  }, [user]);

  const totalMatches = matches.length + historyMatches.length;

  const data = [
    { title: 'Total de jogos', value: totalMatches },
    { title: 'Total de gols', value: userGoals.length },
    { title: 'Média de gols:', value: (userGoals.length / totalMatches).toFixed(2) },
  ]

  return (
    <div>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <main className={styles.main}>
        <div className={styles.hero}>
          {user ? (<UserSticker user={user as User} />) : null}
          <div className={styles.statsContainer}>
            {/* <h1>{user?.name}</h1> */}
            <div className={styles.statsWrapper}>
              {data.map(({ title, value }, index) => (
                <div className={styles.stats} key={index}>
                  <h3>{title}</h3>
                  <div>
                    <span>{value}</span>
                  </div>
                </div>
              ))}
            </div>
            <div className={styles.btnStatsContainer}>
              {/* <BaseButton className={styles.btnStats}>
                <span>Estatísticas completas</span>
              </BaseButton> */}
            </div>
          </div>
        </div>

        <div className={styles.matchesList}>
          <Tabs tabs={[
            {
              title: 'Próximos jogos', component: <MatchesTab matches={matches} />
            },
            {
              title: 'Histórico', component: (<HistoryTab matches={historyMatches} />)
            },
          ]} />
        </div>
      </main >
    </div >
  )
}

type MatchesTabProps = {
  matches: Array<Match>,
}
const MatchesTab = ({ matches }: MatchesTabProps) => {

  const filteredMatches = matches.filter(
    m => m.confirmed.length == 0 || m.confirmed.some(
      confirmed => !confirmed || confirmed.status != "REJECTED")
  );

  return (
    <div className={styles.matchesListBody}>
      {filteredMatches.map(match => (
        <MatchCard
          key={match.uid}
          match={match} />
      ))}
    </div>
  );
}

type HistoryTabProps = {
  matches: Array<Match>
}

const HistoryTab = ({ matches }: HistoryTabProps) => {

  return (
    <div className={styles.matchesListBody}>
      {matches.map((match, index) => (
        <HistoryCard
          key={index.toString()}
          match={match}
        />
      ))}
    </div>

  )
}

export default Home;

